# Generated by Django 6.0.6 on 2026-07-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fridgeitem',
            table='fridge_items',
        ),
    ]
