# Generated by Django 6.0.6 on 2026-08-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_alter_fridgeitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeitem',
            name='model_3d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
