# Generated by Django 6.0.6 on 2026-08-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridgeitem',
            name='model_3d',
        ),
        migrations.AddField(
            model_name='product',
            name='model_2d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
