# Generated by Django 6.0.6 on 2026-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0006_remove_fridgeitem_model_3d_product_model_2d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
