# Generated by Django 6.0.6 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0008_alter_fridgeitem_description_alter_fridgeitem_title_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        ALTER TABLE fridge_product
                        ADD COLUMN IF NOT EXISTS calories double precision NOT NULL DEFAULT 0,
                        ADD COLUMN IF NOT EXISTS protein double precision NOT NULL DEFAULT 0,
                        ADD COLUMN IF NOT EXISTS carbs double precision NOT NULL DEFAULT 0,
                        ADD COLUMN IF NOT EXISTS fat double precision NOT NULL DEFAULT 0;
                    ''',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='calories',
                    field=models.FloatField(default=0),
                ),
                migrations.AddField(
                    model_name='product',
                    name='protein',
                    field=models.FloatField(default=0),
                ),
                migrations.AddField(
                    model_name='product',
                    name='carbs',
                    field=models.FloatField(default=0),
                ),
                migrations.AddField(
                    model_name='product',
                    name='fat',
                    field=models.FloatField(default=0),
                ),
            ],
        ),
    ]
