# Generated by Django 6.0.6 on 2026-08-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fridge',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
